### ISSUE TITLE
composer-cache file permissions

### ISSUE THREAD

**Issue by thomaszbz** [thomaszbz/native-dockerfiles-typo3#19]
Composer complains because of missing file permissions.

> Cannot create cache directory /home/webadmin/.composer/cache/repo/https---packagist.org/, or directory is not writable. Proceeding without cache
> Cannot create cache directory /home/webadmin/.composer/cache/files/, or directory is not writable. > Cannot create cache directory /home/webadmin/.composer/cache/files/, or directory is not writable. Proceeding without cache

This is not a bug (against our feature set) as everything works. We could even investigate if we actually want to make use of composer's caching infrastructure (which has sometimes seemed to be buggy in the past)
![P](https://piwik.2bis10.de/piwik.php?idsite=5&rec=1&url=https://github.com/thomaszbz/native-dockerfiles-typo3/issues/19)

**Comment by thomaszbz** [comment]
Might already be solved with #20

**Comment by pporada-gl** [comment]
What are the permissions on your /home/webadmin/.composer folder? I just installed composer to set up a dev environment for my team with the following line
```
curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer
```

and it set the permissions of the .composer/ folder in my home dir to
```
drwxr-xr-x    3 root        staff      102 Oct  1 10:50 .composer
```

Running this line will fix it.
```
sudo chown -R $USER $HOME/.composer
```

**Comment by pgporada** [comment]
What are the permissions on your /home/webadmin/.composer folder? I just installed composer to set up a dev environment for my team with the following line

```
curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer
```

and it set the permissions of the .composer/ folder in my home dir to

```
drwxr-xr-x    3 root        staff      102 Oct  1 10:50 .composer
```

Running this line will fix it.

```
sudo chown -R $USER $HOME/.composer
```

**Comment by thomaszbz** [comment]
Thanks for your feedback and suggestions. I'm going to fix #20 and see what it does to #19.

Using the [Maintenance section of the manual](https://github.com/thomaszbz/native-dockerfiles-typo3#maintain-typo3-cms-instance), composer should be executed with webadmin permissions. If the home directory of webadmin is writable to webadmin (#20), this could work after #20 is fixed.

Using the examples of the maintenance section, composer already works fine. Just that it can't cache properly.

**Comment by paxperscientiam** [comment]
@pgporada is correct in that `sudo chown -R $USER $HOME/.composer` solves it, at least in my case. For whatever reason, ~/.composer/{cache,composer.json,composer.lock) were owned by root.

**Comment by aescasio** [comment]
@pgporada is right.  this fix the problem in cloud9

**Comment by robertbarros** [comment]
when you installed composer pretty sure you use $sudo .... because of that the folder was created by the root which you do not have permission even if you have admin privilege. the only way to fix that issue it is what @pgporada state. 

type on your terminal:

sudo chown -R $USER $HOME/.composer

this will patch the problem 

JUST TO ADD: if you are setting your php development environment and need disable xDebug make sure disable on php.ini the zend_extension also, on xDebug.remote.enable set as off and xDebug.default.enable set as 0

**Comment by hussain2y2** [comment]
Thanks to all .

**Comment by haifahrul** [comment]
It's work for me.

Thanks all.

**Comment by abrarShariar** [comment]
@pgporada 's last line solved my problem

**Comment by dorelljames** [comment]
Worked for me. Thanks

**Comment by jhfaber** [comment]
@pgporada is correct in that line solved my problem, .composer were owned by root.

**Comment by aymen-ba** [comment]
It solved my problem. Thanks.

**Comment by inoas** [comment]
@pgporada & @paxperscientiam thanks.

**Comment by thomaszbz** [comment]
duplicates #20

**Comment by Abilandou** [comment]
Thanks @pgporada
